file = open("tester3file.txt", "r")
content = file.read()
file.close()
print(content)

file = open("tester3file.txt", "r")
content = file.readline()
print(content)
content = file.readline()
print(content)
content = file.readline()
print(content)
content = file.readline()
print(content)
file.close()